config/routes.rb
Treebook::Application.routes.draw do
  as :user do
    get '/register', to: 'devise/registrations#new',via: :get, as: :register
    get '/login', to: 'devise/sessions#new', via: :get, as: :login
    get '/logout', to: 'devise/sessions#destroy', via: :delete, as: :logout
  end

  devise_for :users, :skip => [:sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Treebook</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Treebook</a>
				</div>	
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li><%= link_to "All Statuses", feed_path %></li>
					</ul>
					<ul class="nav navbar-nav pull-right">
						<% if user_signed_in? %>
							<li><%= link_to "Friends", user_friendships_path %></li>
							<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
							<li><%= link_to "Log Out", logout_path %></li>
						<% else %>
							<li><%= link_to "Register", register_path %></li>
							<li><%= link_to "Login", login_path %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<% flash.each do |type, message| %>
				<div class="alert <%= flash_class type %> alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<%= message %>
				</div>
			<% end %>

			<%= yield %>
		</div>

	</body>
</html>